---
# Homepage services config: PiHole instances (v6+)
# https://gethomepage.dev/widgets/services/pihole/
- DNS (PiHole):
    - PiHole (micro.lan):
        icon: pihole.png
        href: http://micro.lan/admin
        description: PiHole on micro.lan
        widget:
          type: pihole
          url: http://micro.lan
          version: 6
          # key: micro.lan PiHole password or app password
    - PiHole (nuc.lan):
        icon: pihole.png
        href: http://nuc.lan/admin
        description: PiHole on nuc.lan
        widget:
          type: pihole
          url: http://nuc.lan
          version: 6
          # key: nuc.lan PiHole password or app password
    - PiHole (opti.lan):
        icon: pihole.png
        href: http://opti.lan/admin
        description: PiHole on opti.lan
        widget:
          type: pihole
          url: http://opti.lan
          version: 6
          # key: opti.lan PiHole password or app password
