apiVersion: v1
kind: Pod
metadata:
  name: homeassistant
spec:
  #hostUsers: false
  containers:
    - name: homeassistant
      image: ghcr.io/home-assistant/home-assistant:stable
      ports:
        - containerPort: 8123
          hostPort: 8123
      volumeMounts:
        - mountPath: /config
          name: homeassistant-config
        # DBUS required for Bluetooth to work
        - mountPath: /run/dbus
          name: run-dbus
          readOnly: true
      env:
        - name: TZ
          value: Australia/Melbourne
  volumes:
    - name: homeassistant-config
      persistentVolumeClaim:
        claimName: homeassistant-config
    - name: run-dbus
      hostPath:
        path: /run/dbus
        readOnly: true
