apiVersion: v1
kind: Pod
metadata:
  name: pihole
spec:
  containers:
    - name: pihole
      image: docker.io/pihole/pihole:latest
      ports:
        - containerPort: 53
          hostPort: 53
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
      volumeMounts:
        - mountPath: /etc/pihole
          name: pihole-etc
        - mountPath: /etc/dnsmasq.d
          name: pihole-dnsmasq.d
  volumes:
    - name: pihole-etc
      persistentVolumeClaim:
        claimName: pihole-etc
    - name: pihole-dnsmasq.d
      persistentVolumeClaim:
        claimName: pihole-dnsmasq.d
