---
- name: Run the podman system role
  hosts: all
  become: yes
  vars:
    podman_firewall:
      # Home assistant
      - port: 8123/tcp
        state: enabled
      # Pi-hole
      - port: 53/tcp
        state: enabled
      - port: 53/udp
        state: enabled
      - port: 80/tcp
        state: enabled
  roles:
    - fedora.linux_system_roles.podman

