---
- name: Run the podman system role to install Radarr
  # https://hub.docker.com/r/linuxserver/radarr
  hosts: micro.lan
  become: true
  vars:
    podman_run_as_user: media
    podman_run_as_group: media
    podman_firewall:
      # Radarr port
      - port: 7878/tcp
        state: enabled
    podman_quadlet_specs:
      # The yml files need to be defined before
      # the kube file that references them.
      # The other directives need to be under
      # the kube file_src else this does not work!
      - file_src: pod/pod-radarr.yml
      - file_src: kube/radarr.kube
        state: started
  roles:
    - fedora.linux_system_roles.podman
