---
- name: Run the podman system role to install an Apache server for HTTP boot
  # registry.access.redhat.com/ubi10/httpd-24:latest
  hosts: micro.lan
  become: yes
  vars:
    podman_run_as_user: bblasco
    podman_run_as_group: bblasco
    podman_firewall:
      - port: 8800/tcp
        state: enabled
    podman_quadlet_specs:
      # The yml files need to be defined before
      # the kube file that references them.
      # The other directives need to be under
      # the kube file_src else this does not work!
      - file_src: pod/pod-boot-server.yml
      - file_src: kube/boot-server.kube
        state: started
  roles:
    - fedora.linux_system_roles.podman
# Note: There's a reference config settings.json file under files/transmission
