---
- name: Run the podman system role
  hosts: micro.lan
  become: true
  vars:
    podman_run_as_user: bblasco
    podman_run_as_group: bblasco
    podman_firewall:
      - port: 3000/tcp
        state: enabled
    podman_quadlet_specs:
      # The yml files need to be defined before
      # the kube file that references them.
      # The other directives need to be under
      # the kube file_src else this does not work!
      - file_src: pod/pod-homepage.yml
      - file_src: kube/homepage.kube
        state: started
  roles:
    - fedora.linux_system_roles.podman
  tasks:
    - name: Copy Homepage services config into homepage-config volume
      containers.podman.podman_container_copy:
        #src: /files/homepage-config/services.yaml
        src: /tmp/services.yaml
        dest: /app/config/services.yaml
        container: homepage-homepage
      become: false