---
- name: Run the podman system role
  hosts: all
  become: yes
  vars:
    podman_run_as_user: root
    podman_run_as_group: root
    podman_firewall:
      - port: 8080/tcp
        state: enabled
      - port: 8443/tcp
        state: enabled
      - port: 3478/udp
        state: enabled
      - port: 10001/udp
        state: enabled
      - port: 5514/udp
        state: enabled
    podman_quadlet_specs:
      # The yml files need to be defined before
      # the kube file that references them.
      # The other directives need to be under
      # the kube file_src else this does not work!
      #
      # Note: template_src points to files under templates/
      # Note: file_src points to files under files/
      - file_src: pod/pod-unifi.yml
      - file_src: kube/unifi.kube
        state: started
  roles:
    - fedora.linux_system_roles.podman
