---
- name: Run the podman system role
  hosts: micro.lan
  become: yes
  vars:
    podman_run_as_user: root
    podman_run_as_group: root
    podman_firewall:
      - port: 8123/tcp
        state: enabled
    podman_quadlet_specs:
      # The yml files need to be defined before
      # the kube file that references them.
      # The other directives need to be under
      # the kube file_src else this does not work!
      - file_src: pod/pod-homeassistant.yml
      - file_src: kube/homeassistant.kube
        # Setting the state to created because we have to
        # change ownership of files in volumes due to this bug
        # when using userns=keep-id:
        # "podman run is not honoring --userns=keep-id --user=1000:1000 settings while creating volumes"
        # https://github.com/containers/podman/issues/16741
        state: created
  roles:
    - fedora.linux_system_roles.podman
