---
- name: Run the podman system role
  hosts: micro.lan
  become: yes
  vars:
    podman_run_as_user: bblasco
    podman_run_as_group: bblasco
    #podman_firewall:
      #- port: 3001/tcp
      #state: enabled
    podman_quadlet_specs:
      # The yml files need to be defined before
      # the kube file that references them.
      # The other directives need to be under
      # the kube file_src else this does not work!
      - file_src: pod/pod-tailscale.yml
      - file_src: kube/tailscale.kube
        state: started
  roles:
    - fedora.linux_system_roles.podman
