apiVersion: v1
kind: Pod
metadata:
  name: sonarr
  labels:
    io.containers.autoupdate: "registry"
  #annotations:
    # https://www.redhat.com/en/blog/debug-rootless-podman-mounted-volumes
    #run.oci.keep_original_groups: 1
spec:
  containers:
    - name: sonarr
      image: lscr.io/linuxserver/sonarr:latest
      ports:
        - containerPort: 8989
          hostPort: 8989
      volumeMounts:
        - mountPath: /config
          name: sonarr-config
        - mountPath: /mnt/media
          name: sonarr-media
      env:
        - name: PUID
          value: 1000
        - name: PGID
          value: 1000
        - name: TZ
          value: Australia/Melbourne
      securityContext:
        # Set the following permission to allow reading of host's
        # downloads dir (the hostPath mount).
        # This is not a good practice
        # Read more here:
        # https://github.com/containers/podman/issues/3683
        # Udica is possibly a better solution for creating policies
        # relating to containers
        privileged: true
      #securityContext:
        #runAsUser: 1000
        #runAsGroup: 1000
    - name: prowlarr
      image: lscr.io/linuxserver/prowlarr:latest
      ports:
        - containerPort: 9696
          hostPort: 9696
      volumeMounts:
        - mountPath: /config
          name: prowlarr-config
      env:
        - name: PUID
          value: 1000
        - name: PGID
          value: 1000
        - name: TZ
          value: Australia/Melbourne
      securityContext:
        # Set the following permission to allow reading of host's
        # downloads dir (the hostPath mount).
        # This is not a good practice
        # Read more here:
        # https://github.com/containers/podman/issues/3683
        # Udica is possibly a better solution for creating policies
        # relating to containers
        privileged: true
      #securityContext:
        #runAsUser: 1000
        #runAsGroup: 1000

  volumes:
    - name: sonarr-config
      persistentVolumeClaim:
        claimName: sonarr-config
    - name: sonarr-media
      #volumeMode: Filesystem
      hostPath:
        path: /mnt/sg1/media
    - name: prowlarr-config
      persistentVolumeClaim:
        claimName: prowlarr-config

# https://hub.docker.com/r/linuxserver/sonarr
# docker run -d \
#  --name=sonarr \
#  -e PUID=1000 \
#  -e PGID=1000 \
#  -e TZ=Etc/UTC \
#  -p 8989:8989 \
#  -v /path/to/sonarr/data:/config \
#  -v /path/to/tvseries:/tv `#optional` \
#  -v /path/to/downloadclient-downloads:/downloads `#optional` \
#
# https://hub.docker.com/r/linuxserver/prowlarr
#docker run -d \
#  --name=prowlarr \
#  -e PUID=1000 \
#  -e PGID=1000 \
#  -e TZ=Etc/UTC \
#  -p 9696:9696 \
#  -v /path/to/prowlarr/data:/config \
#  --restart unless-stopped \
#  lscr.io/linuxserver/prowlarr:latest
#
