apiVersion: v1
kind: Pod
metadata:
  name: uptime-kuma
  labels:
    io.containers.autoupdate: "registry"
spec:
  containers:
    - name: uptime-kuma
      image: docker.io/louislam/uptime-kuma:1
      ports:
        - containerPort: 3001
          hostPort: 3001
      volumeMounts:
        - mountPath: /app/data
          name: uptime-kuma-app-data
      env:
        - name: TZ
          value: Australia/Melbourne
  volumes:
    - name: uptime-kuma-app-data
      persistentVolumeClaim:
        claimName: uptime-kuma-app-data

# podman run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
